config/routes.rb
Rails.application.routes.draw do
  root to: 'children#index'
  resources :wishlists
  resources :donations
  resources :toys
  resources :children
  resources :users

  get     "/sign_out" => "clearance/sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ApplicationRecord
   has_one_attached :image
   has_many :wishlists
   has_many :toys, through: :wishlists
   has_many :donations
   has_many :users, through: :donations 
   validates :name, presence: true
   validates :age, presence: true
   validates :bio, presence: true
   # validates :image, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :child
  belongs_to :toy
end

app/models/toy.rb
class Toy < ApplicationRecord
    has_many :wishlists
    has_many :children, through: :wishlists
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User


    has_many :donations
    has_many :children, through: :donations

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :username, length: { minimum: 5 }
    validates :email, presence: true
    validates :password, presence:true
    validates :password, length: { in: 3..20 }

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :child
  belongs_to :toy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
    before_action :find_child, only: [:show]

    def index
        @children = Child.all
    end 

    def show
        @wishlists = Wishlist.all
        @donation = Donation.new
        @toys = @child.toys
        @child_donations = Donation.all.select{|w| w.child_id == @child.id}
        
    end 

    def children_page

    end 

    def new
      if current_user
        if admin?
          @donation = Donation.new
          @child = Child.new
        else
          no_permission
        end 
      else 
          no_permission
      end 
    end 

    def create
        @child = Child.new(child_params)
        if @child.valid?
            @child.save
            redirect_to @child
        else
            render :new
        end
    end 


    private

    def find_child
        @child = Child.find(params[:id])
    end 

    def child_params
        params.require(:child).permit(:name, :age, :bio, :image)
    end 

    def admin?
      current_user.username == 'Admin'
    end 

    def no_permission
      flash[:error] = "You must have an admin account to add a child."
          redirect_to children_path
    end 
end




# <%= image_tag("children/1.png", width: '200px') %>
# <%= image_tag("children/2.jpg", width: '200px') %>
# <%= image_tag("children/3.png", width: '200px') %>
# <%= image_tag("children/4.jpg", width: '200px') %>
# <%= image_tag("children/5.png", width: '200px') %>
# <br><br>
# <%= image_tag("children/6.jpg", width: '200px') %>
# <%= image_tag("children/7.jpg", width: '200px') %>
# <%= image_tag("children/8.png", width: '200px') %>
# <%= image_tag("children/9.png", width: '200px') %>
# <%= image_tag("children/10.png", width: '200px') %>

app/controllers/donations_controller.rb
class DonationsController < ApplicationController



  def create

    user_id = current_user.id
    toy_id = params[:donation][:toy_id].to_i    
    child_id = params[:child_id].to_i
    message = params[:donation][:message]
  
    @donation = Donation.new(user_id: user_id, toy_id: toy_id, child_id: child_id, message: message)
    if @donation.valid?
      @donation.save
      child_toys = Wishlist.all.select{|w| w.child_id == child_id}
      child_toys.find{|t| t.toy_id = toy_id}.destroy
      redirect_to child_path("#{child_id}")
    else 
      redirect_to children_path
    end 
  end


  private 

  def donation_params(*args)
    params.require(:donation).permit(*args)
  end 
  



end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = find_user
    @user_donations = Donation.all.select{|d| d.user_id == @user.id}
    @username = @user.username
    
  end

  def new
    @user = User.new
  end 

  def create   
    @user = User.new(user_params)
      if @user.valid?
         @user.save
         redirect_to children_path
      else
        render :new
      end 
  end 

  private

  def user_params
    params.require(:user).permit(:password, :username, :email)
  end 

  private

  def find_user
    User.find(params[:id])
  end 


 
end




  

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/children/index.html.erb
<%if current_user%>
<%= link_to 'Your profile', "/users/#{current_user.id}"%>
<%end%>


<h1>Sponsor A Child</h1>
<div class="container">
    <div class="row">
        <% @children.each do |child| %>
            <div class='col-md-4' >
                <div class="card" style="width: 18rem; margin: 0 auto;">
                    <img class="card-img-top" <%= image_tag(child.image, style: 'width: 100%') %>
                    <div class="card-body">
                        <h2 class="card-title"><%= child.name %></h2>
                        <h5 class="card-text"><%= child.bio %></h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><h5><%= child.age %><h5></li>
                    </ul>
                    <div class="card-body">
                        <h5><%= link_to "Click to Donate!", child%></h5>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>


 

app/views/children/new.html.erb
<h1> Child in Need </h1>
<%= form_for(@child) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :age %>
    <%= f.number_field :age %><br><br>

    <%= f.label :bio %>
    <%= f.text_field :bio %><br><br>

    <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div><br>

    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>
  

app/views/children/show.html.erb
<h1><%= @child.name %></h1>

<div style="width:400px; height:auto">  
<%= link_to image_tag(@child.image, style: 'width: 100%'), children_path %>
</div>
<br>
<h2>Age:<br> <%= @child.age %></h2>
<br>
<h2>Bio:<br> <%= @child.bio %></h2>
<br>

<h2>Wishlist:</h2>
<ul style="list-style-type:none;">
  <% @toys.each do |toy|  %>
  <li>
  <%= link_to toy.name, toy.link %>
  </li>
  <%end%>
</ul>

<%if current_user and @toys.length > 0 %>
<%= render 'donations/form' %>
 <%elsif current_user and @toys.length == 0%>
  <h3>All their wishes have come true!<h3>
 <%else%>
 <h3>You can make a donation by signing in!</h3>
 <%end %>
<br>

<h3>Messages: <h3>
<ul style="list-style-type:none;">
 <% @child_donations.each do|cd|%>
 <% donator = User.all.find{|u| u.id == cd.user_id}%>
 <li>
 <p><%= donator.username%> left you a message!<br> <%=cd.message%></p><br>
 </li>

 <%end%>
 </ul>

app/views/donations/_form.html.erb
<h3>Would you like to make a donation today?</h3>

<%= form_with model: @donation do |f| %>
<input type ="hidden" id="user_id", name = "user_id" value= <%="#{current_user.id}"%>>
<input type ="hidden" id="child_id", name = "child_id" value= <%="#{@child.id}"%>>
<%= collection_select(:donation, :toy_id, @toys, :id, :name) %>  
<%= f.text_area :message %>
<%= f.submit "Create" %>
<% end %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
  </head>

  <body>
    <div class="jumbotron" style="margin-bottom: 0px;">
      <h1>KIDSTARTER</h1>
      <p>Be kind. Donate to a child in need.</p>
    </div>

    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
      <a class="navbar-brand"><%=image_tag("new.png", width: '75px')%></a>
      
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%=link_to "Home", children_path%>
        </li>
        <%if current_user%>
        <li class="nav-item">
          <a class="nav-link"<%=link_to current_user.username, user_path(current_user.id)%>
        </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link"<%=link_to "Sponsors", users_path%>
        </li>
         <%if current_user%>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Sign out", logout_path, method: :delete %>
        </li>
        <%else%>
        <li class="nav-item">
          <a class="nav-link"<%=link_to "Login",sign_in_path%>
        </li>
        <%end%>
        <%if !current_user%>
        <li class="nav-item">
          <a class="nav-link" <%=link_to "Sign up", sign_up_path%>
        </li>
        <%end%>
        </ul>
    </nav>
  <style>
    body {
        background-color:##e8fdff;
        text-align: center;
        font-size: 30px;
        letter-spacing: 2px;
        color: #D50404;
        font-weight: 400;
    }
</style>



    <section>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
        <%= yield %>
    </section>



       
  </body>
</html>



<%# <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/users/">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/sign_up">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/sign_in">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/users">Sponsors</a>
        </li>
        </ul> %>

app/views/users/_form.html.erb
<div class="username-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/index.html.erb
<h1>Donors</h1>

<ul style="list-style-type:none;">
<% @users.each do |user| %>
<li><%= link_to user.username, user %></li>    
<% end %>
</ul>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Donations</h1>
<ul>
<% if !current_user && @user_donations.length == 0%>
    <p>They have not made any donations just yet!<p>
    <%elsif !current_user && @user_donations.length > 0 %>
    <p>Here is what <%@username%> has donated: </p>
    <% @user_donations.each do |donation| %>
    <li style="list-style-type:none;"><%=donation.child.name %> has recieved a <%= donation.toy.name %>!</li>
    <%end%>
  <%elsif current_user.id == params[:id].to_i and @user_donations.size > 0 %>
    <h3>Here is what you have donated:<h3>
    <% @user_donations.each do |donation| %>
    <li style="list-style-type:none;"><%= donation.toy.name %></li>
    <%end %>
    <%elsif current_user.id == params[:id].to_i and @user_donations.size == 0 %>
     <p>You have not made a donation, yet. Jerk!<p><br>
    <%= link_to 'Donate Now', children_path %>
    <%elsif current_user and @user_donations.size > 0 %>
     <h3>Here is what <%=@username%> has donated:<h3>
    <% @user_donations.each do |donation| %>
    <li style="list-style-type:none;"><%=donation.child.name %> has recieved a <%= donation.toy.name %>!</li>
    <%end%>
<% else %>
    <p>No donation has been made yet!</p>
    <%= link_to 'Donate Now', children_path %>
<% end %>
</ul>